//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommunicationPortal.Models.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Folder
    {
        public long FolderId { get; set; }
        public Nullable<long> UserMailboxId { get; set; }
        public Nullable<long> MailboxId { get; set; }
        public byte TypeId { get; set; }
        public byte StatusId { get; set; }
    
        public virtual Mailbox Mailbox { get; set; }
        public virtual UserMailbox UserMailbox { get; set; }
    }
}
