//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommunicationPortal.Models.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMailbox
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserMailbox()
        {
            this.Folders = new HashSet<Folder>();
        }
    
        public long UserMailboxId { get; set; }
        public long UserId { get; set; }
        public bool IsMainContact { get; set; }
        public bool IsDefaultMailbox { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Folder> Folders { get; set; }
        public virtual User User { get; set; }
    }
}
